Repository neXenio/BLE-Indoor-Positioning, pull requests merged in 2018-06, with the labels that each got.

#69 0067 beacon update listeners in beacon manager
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconManager.java
  build.gradle
Labels: bug

#70 0068 provide convenience method for getting locations
  BLE Indoor Positioning/build.gradle
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/Beacon.java
Labels: enhancement

#72 0065 convenience method for location provider
  BLE Indoor Positioning/build.gradle
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/IndoorPositioning.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/Beacon.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/Eddystone.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/IBeacon.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/Location.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/distance/LocationDistanceCalculator.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/projection/SphericalMercatorProjection.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/provider/BeaconLocationProvider.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/provider/EddystoneLocationProvider.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/provider/IBeaconLocationProvider.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/location/distance/BeaconDistanceCalculatorTest.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/location/distance/LocationDistanceCalculatorTest.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/bluetooth/BluetoothClient.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/map/BeaconMap.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#76 0064 provide indoor positioning beacon filter and update listener
  BLE Indoor Positioning/build.gradle
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/IndoorPositioning.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/IBeaconAdvertisingPacket.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/IndoorPositioningBeacon.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/filter/IBeaconFilter.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/BeaconViewFragment.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/chart/BeaconChartFragment.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/map/BeaconMapFragment.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/radar/BeaconRadarFragment.java
Labels: enhancement

#88 0086 negative minor ibeacon
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/IBeaconAdvertisingPacket.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/IBeaconTest.java
  app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/ColorUtil.java
Labels: bug, sample app
