Repository neXenio/BLE-Indoor-Positioning, pull requests merged in 2018-08, with the labels that each got.

#109 0073 too many evaluations
  BLE Indoor Positioning/build.gradle
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/IndoorPositioning.java
Labels: bug, core lib

#115 0113 add method for getting smallest distance
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/AdvertisingPacketFactory.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconUtil.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/distance/BeaconDistanceCalculator.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/provider/BeaconLocationProvider.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconUtilTest.java
Labels: enhancement

#122 fixes #120; adds new tests for AdvertisingUtil.getAdvertisingPacketsBetween
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/AdvertisingPacketUtil.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/advertising/AdvertisingPacketUtilTest.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconTest.java
Labels: bug

#116 Refactored testing util logic for beacon creation
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/AdvertisingPacketUtil.java
  BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/testutil/AbstractBeaconCreator.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/advertising/AdvertisingPacketUtilTest.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconCreator.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconTest.java
  BLE Indoor Positioning/src/test/java/com/nexenio/bleindoorpositioning/ble/beacon/BeaconUtilTest.java
Labels: enhancement
